### ISSUE TITLE
GitLab URLs not starting with "gitlab" are invalid

### ISSUE THREAD

**Issue by zyzzyxdonta** [NFDI4Energy/SMECS#95]
Many institutional GitLab instances will cause an "Invalid URL" error in SMECS as their domain names do not start with "gitlab". I ran into this with `https://codebase.helmholtz.cloud/heliport/heliport`.

https://github.com/NFDI4Energy/SMECS/blob/f929cc6a55ba1fdacc5006033b4c8275ff9fc0a8/meta_creator/url_check_GitLab.py#L22

**Comment by Aidajafarbigloo** [comment]
Hello @zyzzyxdonta 

Thank you for letting us know about the issue. Some changes have been made. Please try the URL again and tell us if you spot any problems. Your feedback is greatly appreciated.

**Comment by zyzzyxdonta** [comment]
Hi @Aidajafarbigloo,

with the new code, it does indeed work. 👍🏻  However, I'm not quite sure if the check is even necessary. The same could be done with one of Django's validators:

```python
from django.core.validators import URLValidator
validate = URLValidator(schemes=["http", "https"])
validate(url)
```

**Comment by Aidajafarbigloo** [comment]
@zyzzyxdonta 

Yes, got your point, and you're right. However, it's useful to know which repository the entered URL is for later on. Then we close this issue.
