### ISSUE TITLE
GitLab contributor name parsing is unstable when encountering strange display names

### ISSUE THREAD

**Issue by zyzzyxdonta** [NFDI4Energy/SMECS#96]
Our GitLab instance gives users display names that contain a department and a number in addition to their lastname, firstname. They look something like this:

```
Doe, John (DEP) - 123456
```

The currently used algorithm for deconstructing this into a first and last name can not really handle this and produces this result:

Given name: `Doe, John John John`
Family name: `(DEP) - 123456`

I wouldn't expect SMECS to handle this case perfectly but the result I get is a bit bizarre nonetheless.

**Comment by sferenz** [comment]
Done within 2dade71532929df075c62dfc2365da433a759458
